import sqlite3

connection=sqlite3.connect('data.db')
cursor=connection.cursor()
cursor.execute('create table IF NOT EXISTS student(name varchar , id int, address varchar)')
#connection.commit()
cursor.execute('insert into student values("sai","123","nehrunagar")')
#connection.commit()
#cursor.execute('delete from student where name="sai"')
connection.commit()
data=cursor.execute('select * from student')
print(list(data))
cursor.execute('update student set name="divya" where name="sai" ')
connection.commit()
data=cursor.execute('select * from student')
print(list(data))
cursor.execute('delete from student')
connection.commit()
data=cursor.execute('select * from student')
print(list(data))
connection.close()
